export const GET_TODOS_BEGIN = "GET_TODOS_BEGIN";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const CREATE_TODOS_BEGIN = "CREATE_TODOS_BEGIN"
export const CREATE_TODOS_SUCCESS = "CREATE_TODOS_SUCCESS"
export const CREATE_TODOS_FAILURE = "CREATE_TODOS_FAILURE"

export const EDIT_TODOS_BEGIN = "EDIT_TODOS_BEGIN"
export const EDIT_TODOS_SUCCESS = "EDIT_TODOS_SUCCESS"
export const EDIT_TODOS_FAILURE = "EDIT_TODOS_FAILURE"

export const DELETE_TODOS_BEGIN = "DELETE_TODOS_BEGIN"
export const DELETE_TODOS_SUCCESS = "DELETE_TODOS_SUCCESS"
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE"

